<<<<<<< HEAD
# Generated by Django 5.2.2 on 2025-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_icon', models.CharField(max_length=50)),
                ('services_title', models.CharField(max_length=50)),
                ('services_des', models.TextField()),
                
            ],
        ),
    ]


=======
# Generated by Django 5.2.2 on 2025-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_icon', models.CharField(max_length=50)),
                ('services_title', models.CharField(max_length=50)),
                ('services_des', models.TextField()),
                
            ],
        ),
    ]


>>>>>>> 876681c8413969cc389dd4e36e4c61eec798164f
