<<<<<<< HEAD
# Generated by Django 5.2.2 on 2025-06-19 20:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='portfolio_title', unique=True),
        ),
    ]
=======
# Generated by Django 5.2.2 on 2025-06-19 20:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='portfolio_title', unique=True),
        ),
    ]
>>>>>>> 876681c8413969cc389dd4e36e4c61eec798164f
