<<<<<<< HEAD
# Generated by Django 5.2.2 on 2025-06-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
=======
# Generated by Django 5.2.2 on 2025-06-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
>>>>>>> 876681c8413969cc389dd4e36e4c61eec798164f
