# Generated by Django 5.2.2 on 2025-06-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_imag',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='portfolio/'),
        ),
    ]
